development:
  adapter: postgresql
  database: ocelots_dev
  user: ocelots
  host: localhost
  pool: 5
  timeout: 5000

test:
  adapter: postgresql
  database: ocelots_test
  user: ocelots
  host: localhost
  pool: 5
  timeout: 5000